
export default function PrivacyPolicyPage() {
  const storeName = process.env.NEXT_PUBLIC_STORE_NAME || 'Our Store';
  
  const genericPolicy = `Last updated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}

This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.

We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.

Interpretation and Definitions
==============================

Interpretation
--------------

The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.

Definitions
-----------

For the purposes of this Privacy Policy:

  * Account means a unique account created for You to access our Service or
    parts of our Service.

  * Company (referred to as either "the Company", "We", "Us" or "Our" in this
    Agreement) refers to ${storeName}.

  * Cookies are small files that are placed on Your computer, mobile device or
    any other device by a website, containing the details of Your browsing
    history on that website among its many uses.

  * Country refers to: India

  * Device means any device that can access the Service such as a computer, a
    cellphone or a digital tablet.

  * Personal Data is any information that relates to an identified or
    identifiable individual.

  * Service refers to the Website.

  * Service Provider means any natural or legal person who processes the data
    on behalf of the Company. It refers to third-party companies or
    individuals employed by the Company to facilitate the Service, to provide
    the Service on behalf of the Company, to perform services related to the
    Service or to assist the Company in analyzing how the Service is used.

  * Usage Data refers to data collected automatically, either generated by the
    use of the Service or from the Service infrastructure itself (for
    example, the duration of a page visit).

  * Website refers to ${storeName}, accessible from your store's URL

  * You means the individual accessing or using the Service, or the company,
    or other legal entity on behalf of which such individual is accessing or
    using the Service, as applicable.
`;
  
  const content = (process.env.NEXT_PUBLIC_PRIVACY_POLICY || genericPolicy).replace(/\[Store Name\]/g, storeName);

  return (
    <div className="container mx-auto px-4 py-12 sm:px-6 lg:px-8">
      <h1 className="text-3xl font-bold tracking-tight text-foreground sm:text-4xl font-headline mb-8 text-center">
        Privacy Policy
      </h1>
      <div className="max-w-4xl mx-auto text-muted-foreground whitespace-pre-wrap text-sm sm:text-base leading-relaxed">
        {content}
      </div>
    </div>
  );
}
